### ISSUE TITLE
using library in processing 3

### ISSUE THREAD

**Issue by eqcq** [davidmoten/predict4java#4]
Hi, is there a way for using your library in processing please ?
I juste want to use a TLE  and retrieve actual lat /long of a satellite

thanks

**Comment by davidmoten** [comment]
Sure have a look at the first test in https://github.com/davidmoten/predict4java/blob/master/src/test/java/com/github/amsacode/predict4java/LEOSatelliteTest.java

**Comment by eqcq** [comment]
thanks I'm going to try from that point
